### ISSUE TITLE
error with npm install

### ISSUE THREAD

**Issue by mgroth0** [OpenBCI/OpenBCI_Hub#48]
just did a clean node reinstall on MacOSX 10.13.3

I can do `npm install electron -g` just fine but `npm install` fails:

```
undefined postinstall /Users/matt/Desktop/OpenBCI_Hub
> node ./node_modules/electron-builder/out/install-app-deps.js

Unhandled rejection Error: Cannot find electron dependency to get electron version in the '/Users/matt/Desktop/OpenBCI_Hub/package.json'
    at Object.<anonymous> (/Users/matt/Desktop/OpenBCI_Hub/node_modules/electron-builder/src/util/util.ts:182:11)
    at Generator.throw (<anonymous>)
From previous event:
    at tsAwaiter (/Users/matt/Desktop/OpenBCI_Hub/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at main (/Users/matt/Desktop/OpenBCI_Hub/node_modules/electron-builder/src/install-app-deps.ts:23:3)
    at Object.<anonymous> (/Users/matt/Desktop/OpenBCI_Hub/node_modules/electron-builder/src/install-app-deps.ts:35:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

npm WARN OpenBCI_Hub No repository field.
npm WARN OpenBCI_Hub No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@1.0.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

```

**Comment by aj-ptw** [comment]
What node version are you using?

**Comment by mgroth0** [comment]
node --version is v9.11.1

**Comment by shirleyzhang867** [comment]
Weird i just tried doing this on a clean install, and the install worked but i am running into another issues. I used node 8.11.1, can you please try using that version?
