### ISSUE TITLE
error from Openbci_Hub_v1.4.2 under windows 10: Cannot find module 'openbci-ganglion'

### ISSUE THREAD

**Issue by Otemo** [OpenBCI/OpenBCI_Hub#50]
When I try to run OpenBciHub 1.4.2 under windows10(64 bit machine), get a java script error right at the start. 

**************
[Main Instruction]
A JavaScript error occurred in the main process
[Content]
Uncaught Exception:
Error: Cannot find module 'openbci-ganglion'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Program Files\OpenBCIHub\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at C:\Program Files\OpenBCIHub\resources\app.asar\background.js:6:32
    at Object.<anonymous> (C:\Program Files\OpenBCIHub\resources\app.asar\background.js:1798:2)
    at Object.<anonymous> (C:\Program Files\OpenBCIHub\resources\app.asar\background.js:1800:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
***************
Thank you

**Comment by wjcroft** [comment]
Forum thread is here,

http://openbci.com/forum/index.php?p=/discussion/1589/error-from-openbci-hub-v1-4-2-under-windows-10-cannot-find-module-openbci-ganglion

Otemo runs Hub v1.3.9 with no problems.

**Comment by aj-ptw** [comment]
looking into this, thanks for the bug report!

**Comment by aj-ptw** [comment]
FIXED! I had to manually build this :( the appveyor is not building correctly, not sure why.

**Comment by Otemo** [comment]
Very thankful to you for your support !

**Comment by Otemo** [comment]
Hi AJ,

Thanks to your help, Openbci Hub v1.4.2 works on my Windows 10 machine. 
new OpenBCI GUI v3.3.0. also could be activated, but it could not conect with cyton board, playback the archive data. No matter how many times I try, OpenBCI GUI v3.3.0. freezes. 

Otemo

**Comment by Otemo** [comment]
Additional information
---
Hub_v.1.3.9 * Gui_v_3.2.0 --> Gui runs without prblems
Hub_v.1.4.2 * Gui_v_3.2.0 --> Gui runs without prblems
Hub_v.1.3.9 * Gui_v_3.3.0 --> Gui Freezes...
Hub_v.1.4.2 * Gui_v_3.3.0 --> Gui Freezes...
---

**Comment by Otemo** [comment]
These issues were solved with the release of GUI v3.3.1.-beta1.
Thank you!
