### ISSUE TITLE
JavaScript error on boot on win32

### ISSUE THREAD

**Issue by baffo32** [OpenBCI/OpenBCI_Hub#51]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'openbci-ganglion'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Program Files\OpenBCIHub\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at C:\Program Files\OpenBCIHub\resources\app.asar\background.js:6:32
    at Object.<anonymous> (C:\Program Files\OpenBCIHub\resources\app.asar\background.js:1798:2)
    at Object.<anonymous> (C:\Program Files\OpenBCIHub\resources\app.asar\background.js:1800:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)

[OK]

**Comment by pspressman** [comment]
I've also had this problem.  Many have suggested using the latest beta upgrade of the Hub, but this didn't work for me.  Any progress?
