### ISSUE TITLE
OpenBCI Hub does not start - Ubuntu 18.04

### ISSUE THREAD

**Issue by winsteadworks** [OpenBCI/OpenBCI_Hub#65]
I could not get the application.linux64 download from the website to run, so I tried downloading this and trying to run Processing IDE. 

I am running a RX 580 amd card with the latest driver and kernel on Ubuntu 18.04

**Any clue on a workaround? Like I mentioned, I do have the GUI running successfully via Processing but I cannot seem to get the Hub to load**

When I try to run Processing IDE, I can get the GUI to load but the Hub never starts and I get this in my console: 
Caught handled GLException: X11GLXDrawableFactory - Could not initialize shared resources for X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x37a54b57, isOwner false, <4a5aab52, 6f3ed31c>[count 0, qsz 0, owner <NULL>]]] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:306)
    [1]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [2]: java.lang.Thread.run(Thread.java:748)
Caused[0] by GLException: main-SharedResourceRunner: Error making temp context(1) current: display 0x7f9a70001200, context 0x7f9a701766f0, drawable X11OnscreenGLXDrawable[Realized true,
	Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@4b44b99d,
	Handle    0x4000002,
	Surface   WrappedSurface[ displayHandle 0x7f9a70001200
, surfaceHandle 0x4000002
, size 64x64
, UOB[ OWNS_SURFACE | WINDOW_INVISIBLE ]
, X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7f9a70001200, owner true, ResourceToolkitLock[obj 0x543ad96e, isOwner true, <67aaf912, 6be2dc05>[count 2, qsz 0, owner <main-SharedResourceRunner>]]], idx 0], visualID 0x1d8, fbConfigID 0x188,
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]],
	chosen    GLCaps[glx vid 0x1d8, fbc 0x188: rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]]]
, surfaceLock <50418b5, 7f750d2>[count 1, qsz 0, owner <main-SharedResourceRunner>]
, X11DummyUpstreamSurfaceHook[pixel 64x64]
, upstreamSurface false ]] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:393)
    [1]: jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
    [2]: jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
    [3]: jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
    [4]: jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:277)
    [5]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [6]: java.lang.Thread.run(Thread.java:748)
Launching application from local data dir
OpenBCI_GUI: hubStart: OS Detected: Linux
Welcome to the Processing-based OpenBCI GUI!
Last update: 9/5/2016
For more information about how to work with this code base, please visit: http://docs.openbci.com/OpenBCI%20Software/
Graphics & GUI Library: ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
attempting to load images for presentation...
DONE loading images!
OpenBCI_GUI::Setup: Is RX mulitcast: false
OpenBCI_GUI::Setup: Has RX joined multicast: false
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at processing.net.Client.<init>(Unknown Source)
	at OpenBCI_GUI$Hub.startTCPClient(OpenBCI_GUI.java:13105)
	at OpenBCI_GUI$Hub.<init>(OpenBCI_GUI.java:13081)
	at OpenBCI_GUI.systemUpdate(OpenBCI_GUI.java:1203)
	at OpenBCI_GUI.draw(OpenBCI_GUI.java:563)
	at processing.core.PApplet.handleDraw(PApplet.java:2429)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
Instantiating hub object...
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
click

**So next I tried to just run the hub separately, in hopes for a work around**
I have tried versions 2.0.0 and 2.0.1, both resulting in same error

**When I followed the README and got to npm install electron-prebuilt -g, I got this:**

npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.4.13 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

/usr/local/lib/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: EACCES: permission denied, link '/usr/local/lib/node_modules/electron-prebuilt/electron-tmp-download-6713-1539750201879/electron-v1.4.13-linux-x64.zip' -> '/home/rig/.electron/electron-v1.4.13-linux-x64.zip'
npm ERR! Linux 4.15.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.4.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rig/Downloads/OpenBCI_Hub-2.0.1/OpenBCI_Ganglion_Electron/npm-debug.log

**Npm start gives this:**
> gulp start

[23:18:49] Using gulpfile ~/Downloads/OpenBCI_Hub-2.0.1/OpenBCI_Ganglion_Electron/gulpfile.js
[23:18:49] Starting 'bundle'...
[23:18:49] Starting 'less'...
[23:18:49] Starting 'environment'...
[23:18:49] Finished 'environment' after 1.77 ms
[23:18:49] Starting 'watch'...
[23:18:49] Finished 'watch' after 5.94 ms
[23:18:49] Finished 'bundle' after 138 ms
[23:18:49] Finished 'less' after 155 ms
[23:18:49] Starting 'build'...
[23:18:49] Finished 'build' after 15 μs
[23:18:49] Starting 'start'...
[23:18:49] Finished 'start' after 3.64 ms
/Downloads/OpenBCI_Hub-2.0.1/OpenBCI_Ganglion_Electron/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by andrewjaykeller** [comment]
Looks like you have a permissions issue related to `npm`.

Can you try the tips on this `npm` official guide? https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by winsteadworks** [comment]
The most recent version from Openbci website
Processing 3.4

**Comment by andrewjaykeller** [comment]
Use the GUI from the development branch, also run with sudo

**Comment by winsteadworks** [comment]
Where is it? @andrewjaykeller

**Comment by winsteadworks** [comment]
If you are referring to this:

https://github.com/OpenBCI/OpenBCI_GUI

I have already ran it in Processing with no luck

**Comment by andrewjaykeller** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v4.0.0-alpha.1

**Comment by andrewjaykeller** [comment]
Are you running processing with sudo? I have linux 18.04 and the GUI runs

**Comment by winsteadworks** [comment]
Also I should mention that I have 6 graphics cards connected. I actually haven't I have been running ./processing with sudo but processing has been running fine, it is when I run the OpenBci GUI that I get the java.lang.RuntimeException: Profile GL3bc is not available on X11GraphicsDevice error. 

This problem is the same when I run it without processing so I don't think it is an issue with processing. Not at my pc at the moment will try when I get back but am going to try it on my laptop to see if it works.

**Comment by retiutut** [comment]
I have two RX 580s and no problems. Closing this issue.
